---
title: "Tutorial with a single-cell dataset"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4L, tibble.print_max = 4L)
knitr::opts_knit$set(warning = FALSE, error = TRUE)
library(infercnaLight)
library(magrittr)
set.seed(1014)
```

## Prepare your data
### Set your genome with `useGenome()` 
```{r}
useGenome('hg19')
retrieveGenome()
```

### Load example data with `useData()`
``` {r}
m = useData(mgh125)
dim(m)
range(m)
lengths(refCells)
```

## Infer CNAs and plot a heatmap
### Infer cells' CNA profiles with `infercna()`
``` {r}
args(infercna)
cna = infercna(m = m, refCells = refCells, n = 5000, noise = 0.1, isLog = TRUE, verbose = FALSE)
cnaM = cna[, !colnames(cna) %in% unlist(refCells)]
```
```{r}
dim(cnaM)
```

```{r}
library(pheatmap)
pheatmap(t(cnaM), cluster_cols = FALSE)
```